version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_service_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
